version: "3.9"

# see run.sh for details on how this docker-compose file should be run

# NOTE, Wireguard does NOT use the TCP protocol. It uses UDP. Therefore,
# to run this docker-compose file in a VM in the cloud, you'll need to
# open up port 58120/UDP

services:

  wireguard:
    image: lscr.io/linuxserver/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      # - SERVERURL=wireguard.domain.com #optional
      - SERVERURL=${EC2_PUBLIC_IP?Variable not set} #optional
      - SERVERPORT=51820 #optional
      - PEERS=1 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
    volumes:
      - ./config:/config
      # apparently this volume is for when your host OS is older... I'm not sure
      - /lib/modules:/lib/modules
      # linux kernel headers for AmazonLinux2
      - /usr/src:/usr/src
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
