# NOTE: This file contains a subset of the pre-commit hooks
# in the rootski/ folder that are applicable to React/Typescript-code only.
# There is a lot of duplicated code in here. This is an acceptable
# tradeoff for the benefit: if someone opens this folder as their
# vscode workspace, pre-commit will still work on commit.

############################
# --- Pre-Commit Hooks --- #
############################

repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        args: ["--tab-width=2", "--write=src/**/*.ts{,x}"]
        # only include files in the rootski_frontend folder
        files: ^rootski_frontend/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      # Fails if there are any ">>>>>" lines in files due to merge conflicts.
      - id: check-merge-conflict
      # Trims trailing whitespace. Allow a single space on the end of .md lines for hard line breaks.
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      # Makes sure files end in a newline and only a newline;
      # we include CSV since a lot of the files already in our git LFS store are csv and json
      - id: end-of-file-fixer
        exclude_types: [csv, svg]
      # Attempts to load all TOML files to verify syntax.
      - id: check-toml
      # Attempts to load all yaml files to verify syntax; unsafe: only check syntax, do not load yaml
      - id: check-yaml
        args: ["--unsafe"]
      # Check for symlinks that do not point to anything.
      - id: check-symlinks
      # Fail if staged files are above a certain size.
      # To add a large file, use 'git lfs track <file>; git add <file> to track large files with
      # git-lfs rather than commiting them directly to the git history
      - id: check-added-large-files
        args: ["--maxkb=500"]
      # Sort requirements in requirements.txt files.
      - id: requirements-txt-fixer
      # Prevent addition of new git submodules.
      - id: forbid-new-submodules
      # Prevent committing directly to trunk (since Bitbucket wants us to pay for this feature)
      - id: no-commit-to-branch
        args: ["--branch=trunk"]
      # Detects *your* aws credentials from your ~/.aws/credentials file
      - id: detect-aws-credentials
      # Detects the presence of private keys
      - id: detect-private-key
