# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Rootski CI

on:
  push:
    # CI is triggered when commits enter these branches (on the GitHub remote server, not locally)
    branches: [ trunk ]
  pull_request:
    # CI is triggered when PRs are opened with these branches as targets
    branches: [ trunk ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    # checkout the code
    - uses: actions/checkout@v2
    
    # install python
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
        
    # install docker
    - name: install docker
      uses: actions/setup-docker@1.0.8
    
    - name: install dependencies
      run: |
        # install global python dependencies
        make install
        
        # install python dependencies specific to the backend code
        cd rootski_api
        make install
        
        # install docker-compose because it is needed to run the tests
        make install-docker-compose
        
        # run the tests
        make full-test-ci
        
    - name: run tests and other code quality checks
      run: |
        # check the backend code quality (formatting, linting, static code checks)
        cd rootski_api
        make check-code-quality-ci
        
        # run the backend tests
        make full-tests-ci
        
        
        
